### ISSUE TITLE
Create NotebookLM podcast

### ISSUE THREAD

**Issue by ghost** [oznewman/ilya#1]
# Tasks
- [x] Figure out optimal ordering
- [x] Create a course roadmap
- [ ] Draft system prompt for entire course
- [ ] Create a podcast for every episode
